### ISSUE TITLE
FM Sound

### ISSUE THREAD

**Issue by hansbonini** [SukkoPera/SMSPlusPlus#3]
Do you think that is possible to use Arduino to produce FM Sound?

**Comment by SukkoPera** [comment]
Definitely no.

**Comment by Xenogears75** [comment]
Maybe you could explain a certain issue to me. If I Hit Button B or C fast, my Logic Probe states the correct timing on the Inputs. On the Outputs, the Press of the Buttons is delayed and often Skipped. E.g. if I press the Button 5 times fast, I only get to Signals "low" on 12 and 13. I use Ardurino Pro Mini for Coding.
