### ISSUE TITLE
Digital Pin 5 - Controller Type Out?

### ISSUE THREAD

**Issue by TimRegeant** [SukkoPera/SMSPlusPlus#5]
This pin is described in the source

>  /* Controller Type Out: this will be HIGH when a MegaDrive 3- or 6-button pad is							
>   detected. Useful for driving a multiplexer, see wiki.							
>  */							

But I don't see anything on the wiki about this.  Where is this feature explained?

**Comment by SukkoPera** [comment]
There's no documentation, and I can't even remember exactly what was in my mind. I guess you're on your own.
